### ISSUE TITLE
Hello world example 404s

### ISSUE THREAD

**Issue by cpsievert** [dreamRs/gfonts#2]
Great idea for a package! I really like to use it and recommend it, but unfortunately both `download_font()` and `setup_font()` seem to always 404?

```r
library(gfonts)
setup_font(
  id = "roboto",
  output_dir = "path/to"
)
```

```r
Error: Not Found (HTTP 404)
```

**Comment by pvictor** [comment]
Thanks!
Oups a last minute change bug...
The error occurs when no variants are supplied, that's fixed.
Otherwise you have to explicitly specify variant(s) to download : 

```r
download_font(
  id = "roboto", 
  variants = c("regular", "italic"),
  output_dir = "path/to"
)
```

Victor

**Comment by cpsievert** [comment]
Wonderful, thank you, and thanks for all your other great contributions to the shiny ecosystem!
