### ISSUE TITLE
[Bug] The workflow does not seem to work for Kiwi Maru font ?

### ISSUE THREAD

**Issue by HenriFreixe** [dreamRs/gfonts#7]
First of all, thank you so much for this very useful package.
For a project I am currently working on, I would like to use the Kiwi Maru Google Font, which is part of the available fonts as it currently site 869 in terms of popularity in the `get_all_fonts()` data.frame, under the "kiwi-maru" id.

I am perfectly able to both download the font and generate the css with the following function :
```
if(!dir.exists("fonts")) dir.create("fonts")
setup_font(id = "kiwi-maru", output_dir = "fonts",
           variants = "regular", prefer_local_source = FALSE)
```

However, I get the following error when running the `use_font()` function as follows :
```
use_font("kiwi-maru", "fonts/css/kiwi-maru.css", selector = "body")
```

`Erreur : use_font: font not found, please check or provide argument CSS.`

Please note that I have tried the very same workflow with the fonts Open Sans, Roboto, Noto Sans SC and Noto Serif without running into any issue.

Would you happen to know what the issue may be ?

Thank you very much for your help, and above all for the awesome package !

**Comment by pvictor** [comment]
Hello Henri,
Thanks for the encouragement!

`kiwi-maru` appears to be a recently added font and the package use an internal font reference dataset that is not up to date.
If you re-install {gfonts} from GitHub it should work, otherwise you have to provide the `css` argument in `use_font()` like this: 

```r
use_font("kiwi-maru", "fonts/css/kiwi-maru.css", selector = "body", css = "font-family: 'Kiwi Maru', serif;")
```

Victor

**Comment by HenriFreixe** [comment]
Hello Victor,

Thank you very much, both options worked like a charm for me !

Best,

Henri
